# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NLT module Astrobiologie
author: Coen Klein Douwel
logo: logo.jpg

sphinx:
  language: nl
  locale_dirs: ["locale"]


copyright: '2025' 


parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath

execute:
  execute_notebooks: force

latex:   
  latex_documents:
    targetname: book.tex
packages:
    - mhchem
    - chemfig
preamble: |
    \usepackage[version=4]{mhchem}
    \usepackage{chemfig}

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/executablebooks/jupyter-book
  path_to_book: docs
  branch: master

html:
  baseurl: /Astro-online/
  use_issues_button: true
  use_repository_button: true
  theme: sphinx_book_theme
  mathjax_config:
    TeX:
      equationNumbers: { autoNumber: "AMS" }
  extra_css:
    - _static/custom.css
  extra_footer: |
   <img src="_static/cc.svg" alt="BY" style="height:1em; vertical-align:middle;"><img src="_static/by.svg" alt="BY" style="height:1em; vertical-align:middle;">
  


